{% set name = "astrowidgets" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 785521fbdf0c71041e50140ff0334c33e75c5da6fb3d2115a4f5dd7525e13555

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - astropy
    - ginga
    - ipywidgets >=7.5
    - ipyevents >=0.6.3
    - python >={{ python_min }}
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - astrowidgets

about:
  home: https://astrowidgets.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Astronomy widgets for the Jupyter notebook and JupyterLab
  description: |
    astrowidgets provides an image viewer Jupyter widget for the Jupyter
    notebook and JupyterLab.
  doc_url: https://astrowidgets.readthedocs.io
  dev_url: https://github.com/astropy/astrowidgets

extra:
  recipe-maintainers:
    - mwcraig
