{% set name = "astrowidgets" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f913ec7f682e5e6b61ccacde9a46a40cf6012ccd4a76d4a216b79ad33eda473d

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - astropy
    - ginga
    - ipywidgets >=7.5
    - ipyevents >=0.6.3
    - python >={{ python_min }}
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - astrowidgets

about:
  home: https://astrowidgets.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Astronomy widgets for the Jupyter notebook and JupyterLab
  description: |
    astrowidgets provides an image viewer Jupyter widget for the Jupyter
    notebook and JupyterLab.
  doc_url: https://astrowidgets.readthedocs.io
  dev_url: https://github.com/astropy/astrowidgets

extra:
  recipe-maintainers:
    - mwcraig
